// <auto-generated />
using System;
using DMO.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DMO.Infrastructure.Migrations
{
    [DbContext(typeof(DmoDbContext))]
    [Migration("20260922001757_TemplateModuleComposition")]
    partial class TemplateModuleComposition
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DMO.Infrastructure.Persistence.Entities.AdminAccountEntity", b =>
                {
                    b.Property<Guid>("AdminId")
                        .HasColumnType("uuid")
                        .HasColumnName("admin_id");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<string>("AuthIdentityId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("auth_identity_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("AdminId");

                    b.HasIndex("Active")
                        .HasDatabaseName("admin_accounts_active_idx")
                        .HasFilter("\"active\"");

                    b.HasIndex("AuthIdentityId")
                        .IsUnique()
                        .HasDatabaseName("admin_accounts_auth_identity_id_key");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("admin_accounts_email_key");

                    b.ToTable("admin_accounts", null, t =>
                        {
                            t.HasCheckConstraint("admin_accounts_auth_identity_id_required_check", "btrim(auth_identity_id) <> ''");

                            t.HasCheckConstraint("admin_accounts_email_required_check", "btrim(email) <> ''");

                            t.HasCheckConstraint("admin_accounts_singleton_id_check", "admin_id = '00000000-0000-4000-8000-0000000000ad'::uuid");
                        });
                });

            modelBuilder.Entity("DMO.Infrastructure.Persistence.Entities.TemplateEntity", b =>
                {
                    b.Property<Guid>("TemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("template_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("LandingDestinationId")
                        .HasColumnType("text")
                        .HasColumnName("landing_destination_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("TemplateId");

                    b.ToTable("templates", (string)null);
                });

            modelBuilder.Entity("DMO.Infrastructure.Persistence.Entities.TemplateModuleEntity", b =>
                {
                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("template_id");

                    b.Property<string>("ModuleId")
                        .HasColumnType("text")
                        .HasColumnName("module_id");

                    b.Property<int>("PresentationOrder")
                        .HasColumnType("integer")
                        .HasColumnName("presentation_order");

                    b.HasKey("TemplateId", "ModuleId");

                    b.HasIndex("TemplateId", "PresentationOrder")
                        .IsUnique()
                        .HasDatabaseName("template_modules_template_order_key");

                    b.ToTable("template_modules", (string)null);
                });

            modelBuilder.Entity("DMO.Infrastructure.Persistence.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<string>("AuthIdentityId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("auth_identity_id");

                    b.Property<string>("CompanyNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("company_number");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Role")
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<Guid?>("TemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("template_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("UserId");

                    b.HasIndex("Active")
                        .HasDatabaseName("users_active_idx")
                        .HasFilter("\"active\"");

                    b.HasIndex("AuthIdentityId")
                        .IsUnique()
                        .HasDatabaseName("users_auth_identity_id_key");

                    b.HasIndex("CompanyNumber")
                        .IsUnique()
                        .HasDatabaseName("users_company_number_key");

                    b.HasIndex("TemplateId");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("users_auth_identity_id_required_check", "btrim(auth_identity_id) <> ''");

                            t.HasCheckConstraint("users_company_number_required_check", "btrim(company_number) <> ''");

                            t.HasCheckConstraint("users_email_required_check", "btrim(email) <> ''");
                        });
                });

            modelBuilder.Entity("DMO.Infrastructure.Persistence.Entities.TemplateModuleEntity", b =>
                {
                    b.HasOne("DMO.Infrastructure.Persistence.Entities.TemplateEntity", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("DMO.Infrastructure.Persistence.Entities.UserEntity", b =>
                {
                    b.HasOne("DMO.Infrastructure.Persistence.Entities.TemplateEntity", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Template");
                });
#pragma warning restore 612, 618
        }
    }
}
