// <auto-generated />
using System;
using DMO.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DMO.Infrastructure.Migrations
{
    [DbContext(typeof(DmoDbContext))]
    [Migration("20260922232349_ToolJobOnDomainCore")]
    partial class ToolJobOnDomainCore
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DMO.Infrastructure.Persistence.Entities.AdminAccountEntity", b =>
                {
                    b.Property<Guid>("AdminId")
                        .HasColumnType("uuid")
                        .HasColumnName("admin_id");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<string>("AuthIdentityId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("auth_identity_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("AdminId");

                    b.HasIndex("Active")
                        .HasDatabaseName("admin_accounts_active_idx")
                        .HasFilter("\"active\"");

                    b.HasIndex("AuthIdentityId")
                        .IsUnique()
                        .HasDatabaseName("admin_accounts_auth_identity_id_key");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("admin_accounts_email_key");

                    b.ToTable("admin_accounts", null, t =>
                        {
                            t.HasCheckConstraint("admin_accounts_auth_identity_id_required_check", "btrim(auth_identity_id) <> ''");

                            t.HasCheckConstraint("admin_accounts_email_required_check", "btrim(email) <> ''");

                            t.HasCheckConstraint("admin_accounts_singleton_id_check", "admin_id = '00000000-0000-4000-8000-0000000000ad'::uuid");
                        });
                });

            modelBuilder.Entity("DMO.Infrastructure.Persistence.Entities.BqContextEntity", b =>
                {
                    b.Property<Guid>("BqId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("bq_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("JobOnId")
                        .HasColumnType("uuid")
                        .HasColumnName("jobon_id");

                    b.Property<Guid>("ToolId")
                        .HasColumnType("uuid")
                        .HasColumnName("tool_id");

                    b.Property<string>("ToolLot")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tool_lot");

                    b.Property<string>("ToolReference")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tool_reference");

                    b.Property<string>("ToolType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tool_type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("BqId");

                    b.HasIndex("JobOnId")
                        .IsUnique()
                        .HasDatabaseName("bq_contexts_jobon_key");

                    b.HasIndex("ToolId")
                        .HasDatabaseName("IX_bq_contexts_tool_id");

                    b.ToTable("bq_contexts", null, t =>
                        {
                            t.HasCheckConstraint("bq_contexts_tool_lot_required_check", "btrim(tool_lot) <> ''");

                            t.HasCheckConstraint("bq_contexts_tool_reference_required_check", "btrim(tool_reference) <> ''");

                            t.HasCheckConstraint("bq_contexts_tool_type_check", "tool_type = 'BQ'");
                        });
                });

            modelBuilder.Entity("DMO.Infrastructure.Persistence.Entities.CmContextEntity", b =>
                {
                    b.Property<Guid>("CmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("cm_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("JobOnId")
                        .HasColumnType("uuid")
                        .HasColumnName("jobon_id");

                    b.Property<Guid>("ToolId")
                        .HasColumnType("uuid")
                        .HasColumnName("tool_id");

                    b.Property<string>("ToolLot")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tool_lot");

                    b.Property<string>("ToolReference")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tool_reference");

                    b.Property<string>("ToolType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tool_type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("CmId");

                    b.HasIndex("JobOnId")
                        .IsUnique()
                        .HasDatabaseName("cm_contexts_jobon_key");

                    b.HasIndex("ToolId")
                        .HasDatabaseName("IX_cm_contexts_tool_id");

                    b.ToTable("cm_contexts", null, t =>
                        {
                            t.HasCheckConstraint("cm_contexts_tool_lot_required_check", "btrim(tool_lot) <> ''");

                            t.HasCheckConstraint("cm_contexts_tool_reference_required_check", "btrim(tool_reference) <> ''");

                            t.HasCheckConstraint("cm_contexts_tool_type_check", "tool_type = 'CM'");
                        });
                });

            modelBuilder.Entity("DMO.Infrastructure.Persistence.Entities.JobOnEntity", b =>
                {
                    b.Property<Guid>("JobOnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("jobon_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("CopiedFromJobOnId")
                        .HasColumnType("uuid")
                        .HasColumnName("copied_from_jobon_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Machine")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("machine");

                    b.Property<DateOnly?>("ProductionDate")
                        .HasColumnType("date")
                        .HasColumnName("production_date");

                    b.Property<string>("ProductionNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("production_number");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reference");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("JobOnId");

                    b.HasIndex("CopiedFromJobOnId")
                        .HasDatabaseName("IX_job_ons_copied_from_jobon_id");

                    b.HasIndex("Reference", "ProductionNumber")
                        .IsUnique()
                        .HasDatabaseName("job_ons_reference_production_number_key");

                    b.ToTable("job_ons", null, t =>
                        {
                            t.HasCheckConstraint("job_ons_machine_check", "machine IN ('B1','B2','B3','C1','C2','C3')");

                            t.HasCheckConstraint("job_ons_production_number_required_check", "btrim(production_number) <> ''");

                            t.HasCheckConstraint("job_ons_reference_required_check", "btrim(reference) <> ''");
                        });
                });

            modelBuilder.Entity("DMO.Infrastructure.Persistence.Entities.MfContextEntity", b =>
                {
                    b.Property<Guid>("MfId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("mf_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("JobOnId")
                        .HasColumnType("uuid")
                        .HasColumnName("jobon_id");

                    b.Property<Guid>("ToolId")
                        .HasColumnType("uuid")
                        .HasColumnName("tool_id");

                    b.Property<string>("ToolLot")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tool_lot");

                    b.Property<string>("ToolReference")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tool_reference");

                    b.Property<string>("ToolType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tool_type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("MfId");

                    b.HasIndex("JobOnId")
                        .IsUnique()
                        .HasDatabaseName("mf_contexts_jobon_key");

                    b.HasIndex("ToolId")
                        .HasDatabaseName("IX_mf_contexts_tool_id");

                    b.ToTable("mf_contexts", null, t =>
                        {
                            t.HasCheckConstraint("mf_contexts_tool_lot_required_check", "btrim(tool_lot) <> ''");

                            t.HasCheckConstraint("mf_contexts_tool_reference_required_check", "btrim(tool_reference) <> ''");

                            t.HasCheckConstraint("mf_contexts_tool_type_check", "tool_type = 'MF'");
                        });
                });

            modelBuilder.Entity("DMO.Infrastructure.Persistence.Entities.TemplateEntity", b =>
                {
                    b.Property<Guid>("TemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("template_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("LandingDestinationId")
                        .HasColumnType("text")
                        .HasColumnName("landing_destination_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("TemplateId");

                    b.ToTable("templates", (string)null);
                });

            modelBuilder.Entity("DMO.Infrastructure.Persistence.Entities.TemplateModuleEntity", b =>
                {
                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("template_id");

                    b.Property<string>("ModuleId")
                        .HasColumnType("text")
                        .HasColumnName("module_id");

                    b.Property<int>("PresentationOrder")
                        .HasColumnType("integer")
                        .HasColumnName("presentation_order");

                    b.HasKey("TemplateId", "ModuleId");

                    b.HasIndex("TemplateId", "PresentationOrder")
                        .IsUnique()
                        .HasDatabaseName("template_modules_template_order_key");

                    b.ToTable("template_modules", (string)null);
                });

            modelBuilder.Entity("DMO.Infrastructure.Persistence.Entities.ToolEntity", b =>
                {
                    b.Property<Guid>("ToolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("tool_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Lot")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lot");

                    b.Property<string>("Processo")
                        .HasColumnType("text")
                        .HasColumnName("processo");

                    b.Property<int?>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reference");

                    b.Property<string>("ToolType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tool_type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("ToolId");

                    b.HasIndex("Reference")
                        .HasDatabaseName("tools_reference_idx");

                    b.HasIndex("ToolType", "Reference", "Lot")
                        .IsUnique()
                        .HasDatabaseName("tools_type_reference_lot_key");

                    b.ToTable("tools", null, t =>
                        {
                            t.HasCheckConstraint("tools_lot_required_check", "btrim(lot) <> ''");

                            t.HasCheckConstraint("tools_processo_check", "processo IS NULL OR processo IN ('NNPB','PS')");

                            t.HasCheckConstraint("tools_quantity_check", "quantity IS NULL OR quantity >= 0");

                            t.HasCheckConstraint("tools_reference_required_check", "btrim(reference) <> ''");

                            t.HasCheckConstraint("tools_type_check", "tool_type IN ('CM','MF','BQ')");
                        });
                });

            modelBuilder.Entity("DMO.Infrastructure.Persistence.Entities.ToolMachineEntity", b =>
                {
                    b.Property<Guid>("ToolMachineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("tool_machine_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Machine")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("machine");

                    b.Property<Guid>("ToolId")
                        .HasColumnType("uuid")
                        .HasColumnName("tool_id");

                    b.HasKey("ToolMachineId");

                    b.HasIndex("Machine")
                        .HasDatabaseName("tool_machines_machine_idx");

                    b.HasIndex("ToolId", "Machine")
                        .IsUnique()
                        .HasDatabaseName("tool_machines_tool_machine_key");

                    b.ToTable("tool_machines", null, t =>
                        {
                            t.HasCheckConstraint("tool_machines_machine_check", "machine IN ('B1','B2','B3','C1','C2','C3')");
                        });
                });

            modelBuilder.Entity("DMO.Infrastructure.Persistence.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<string>("AuthIdentityId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("auth_identity_id");

                    b.Property<string>("CompanyNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("company_number");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Role")
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<Guid?>("TemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("template_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("UserId");

                    b.HasIndex("Active")
                        .HasDatabaseName("users_active_idx")
                        .HasFilter("\"active\"");

                    b.HasIndex("AuthIdentityId")
                        .IsUnique()
                        .HasDatabaseName("users_auth_identity_id_key");

                    b.HasIndex("CompanyNumber")
                        .IsUnique()
                        .HasDatabaseName("users_company_number_key");

                    b.HasIndex("TemplateId");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("users_auth_identity_id_required_check", "btrim(auth_identity_id) <> ''");

                            t.HasCheckConstraint("users_company_number_required_check", "btrim(company_number) <> ''");

                            t.HasCheckConstraint("users_email_required_check", "btrim(email) <> ''");
                        });
                });

            modelBuilder.Entity("DMO.Infrastructure.Persistence.Entities.BqContextEntity", b =>
                {
                    b.HasOne("DMO.Infrastructure.Persistence.Entities.JobOnEntity", null)
                        .WithMany()
                        .HasForeignKey("JobOnId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_bq_contexts_job_ons_jobon_id");

                    b.HasOne("DMO.Infrastructure.Persistence.Entities.ToolEntity", null)
                        .WithMany()
                        .HasForeignKey("ToolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_bq_contexts_tools_tool_id");
                });

            modelBuilder.Entity("DMO.Infrastructure.Persistence.Entities.CmContextEntity", b =>
                {
                    b.HasOne("DMO.Infrastructure.Persistence.Entities.JobOnEntity", null)
                        .WithMany()
                        .HasForeignKey("JobOnId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_cm_contexts_job_ons_jobon_id");

                    b.HasOne("DMO.Infrastructure.Persistence.Entities.ToolEntity", null)
                        .WithMany()
                        .HasForeignKey("ToolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_cm_contexts_tools_tool_id");
                });

            modelBuilder.Entity("DMO.Infrastructure.Persistence.Entities.JobOnEntity", b =>
                {
                    b.HasOne("DMO.Infrastructure.Persistence.Entities.JobOnEntity", null)
                        .WithMany()
                        .HasForeignKey("CopiedFromJobOnId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_job_ons_job_ons_copied_from_jobon_id");
                });

            modelBuilder.Entity("DMO.Infrastructure.Persistence.Entities.MfContextEntity", b =>
                {
                    b.HasOne("DMO.Infrastructure.Persistence.Entities.JobOnEntity", null)
                        .WithMany()
                        .HasForeignKey("JobOnId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_mf_contexts_job_ons_jobon_id");

                    b.HasOne("DMO.Infrastructure.Persistence.Entities.ToolEntity", null)
                        .WithMany()
                        .HasForeignKey("ToolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_mf_contexts_tools_tool_id");
                });

            modelBuilder.Entity("DMO.Infrastructure.Persistence.Entities.TemplateModuleEntity", b =>
                {
                    b.HasOne("DMO.Infrastructure.Persistence.Entities.TemplateEntity", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("DMO.Infrastructure.Persistence.Entities.ToolMachineEntity", b =>
                {
                    b.HasOne("DMO.Infrastructure.Persistence.Entities.ToolEntity", "Tool")
                        .WithMany("Machines")
                        .HasForeignKey("ToolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tool");
                });

            modelBuilder.Entity("DMO.Infrastructure.Persistence.Entities.UserEntity", b =>
                {
                    b.HasOne("DMO.Infrastructure.Persistence.Entities.TemplateEntity", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Template");
                });

            modelBuilder.Entity("DMO.Infrastructure.Persistence.Entities.ToolEntity", b =>
                {
                    b.Navigation("Machines");
                });
#pragma warning restore 612, 618
        }
    }
}
