using DMO.Application.Access;
using Microsoft.AspNetCore.Authorization;
using Microsoft.Extensions.DependencyInjection;

namespace DMO.Web.Authorization;

/// <summary>
/// Declarative ASP.NET authorization projection of the canonical Module identities.
/// </summary>
/// <remarks>
/// <para>
/// One policy per canonical <see cref="ModuleCatalog"/> identity; policy names are derived
/// deterministically from the Module id (<see cref="PolicyName"/>). Each policy contains
/// exactly one <see cref="ModuleAuthorizationRequirement"/> whose only fact is the canonical
/// Module id — policies are generated by iterating the catalog, so they can never become an
/// independent permission catalogue or a hand-maintained permission matrix.
/// </para>
/// <para>
/// Future protected routes/actions declare e.g.
/// <c>[Authorize(Policy = ModuleAuthorizationPolicies.PolicyName(ModuleCatalog.ControloApprove))]</c>
/// — the attribute names the Module identity, nothing else. Phase 1 has no operational routes
/// consuming these policies; the mechanism is ready and tested. No placeholder pages.
/// </para>
/// </remarks>
public static class ModuleAuthorizationPolicies
{
    /// <summary>
    /// Deterministic policy name derived from a canonical Module id.
    /// </summary>
    public static string PolicyName(ModuleId id) => $"dmo.module.{id.Value}";

    /// <summary>
    /// Registers ASP.NET authorization with exactly one policy per canonical Module and the
    /// <see cref="ModuleAuthorizationHandler"/>.
    /// </summary>
    /// <param name="services">The service collection.</param>
    /// <returns>The same service collection, for chaining.</returns>
    public static IServiceCollection AddModuleAuthorization(this IServiceCollection services)
    {
        ArgumentNullException.ThrowIfNull(services);

        services.AddAuthorization(options => AddModulePolicies(options));

        // The handler consumes scoped services (ICurrentAccountContext, IModuleAccessService),
        // so it is registered scoped — one instance per request scope. (Mechanical adjustment
        // to the singleton registration sketched in the plan: scoped lifetime is required for
        // constructor injection of scoped services; the projection semantics are unchanged.)
        services.AddScoped<IAuthorizationHandler, ModuleAuthorizationHandler>();

        return services;
    }

    /// <summary>
    /// Adds the 13 canonical Module policies onto the given authorization options.
    /// </summary>
    /// <remarks>
    /// Exposed for direct composition/tests; each policy = one
    /// <see cref="ModuleAuthorizationRequirement"/> for the Module id.
    /// </remarks>
    public static void AddModulePolicies(AuthorizationOptions options)
    {
        ArgumentNullException.ThrowIfNull(options);

        foreach (var entry in ModuleCatalog.All)
        {
            var id = entry.Id;
            options.AddPolicy(PolicyName(id), policy =>
                policy.Requirements.Add(new ModuleAuthorizationRequirement(id)));
        }
    }
}