using DMO.Application.Tools;
using DMO.Domain.Tools;
using DMO.Web.Frontend.Shared.Contracts;

namespace DMO.Web.Pages.JobOn;

/// <summary>
/// The P2-T04 domain orchestration around the accepted P2-T03 ToolPicker primitive.
/// </summary>
/// <remarks>
/// Authority: P2-T04 contract §9 (one shared search/select/create orchestration), §18.1/§18.2 and the
/// architect plan review §23 item N3.
/// <para>
/// The primitive stays presentation/mechanics only. This adapter owns the search criteria, the
/// candidate mapping, the opaque→canonical mapping, the explicit-selection latch, the origin
/// association and the return orchestration.
/// </para>
/// <para>
/// <b>Opaque keys stay opaque.</b> A candidate key is generated by this adapter and is never a
/// canonical identity, a route, a filename or a URL: the canonical <c>tool_id</c> is resolved through
/// this adapter's own state, never by parsing display text, a reference, a lot or a machine.
/// </para>
/// <para>
/// <b>Never auto-select.</b> Mapping a search result produces candidates with no controlled
/// selection, including when exactly one item is returned; only an explicit human selection produces
/// a canonical identity, and the first one is latched for the duration of the interaction so a
/// second event cannot change it.
/// </para>
/// </remarks>
public sealed class JobOnToolPickerAdapter
{
    /// <summary>The opaque per-interaction origin token prefix; never a canonical identity.</summary>
    public const string OriginTokenPrefix = "jobon-tool-origin";

    /// <summary>The opaque candidate key prefix; never a canonical identity.</summary>
    public const string CandidateKeyPrefix = "tool-candidate";

    private readonly Dictionary<string, ToolSearchItem> _itemsByKey = new(StringComparer.Ordinal);
    private ToolSelection? _selection;

    /// <summary>Creates the adapter for one origin slot over one bounded search result.</summary>
    public JobOnToolPickerAdapter(ToolContextType contextType, IReadOnlyList<ToolSearchItem> items)
    {
        ArgumentNullException.ThrowIfNull(items);

        ContextType = contextType;
        ExpectedType = ToolTokens.RequiredToolType(contextType);

        var candidates = new List<ToolPickerCandidatePresentation>(items.Count);
        var map = new List<ToolCandidateEntry>(items.Count);

        for (var index = 0; index < items.Count; index++)
        {
            var item = items[index];
            var key = $"{CandidateKeyPrefix}-{SlotToken}-{index}";

            _itemsByKey[key] = item;
            map.Add(new ToolCandidateEntry(key, item.ToolId));

            candidates.Add(ToolPickerCandidatePresentation.Create(
                key,
                AccessibleContext(item),
                Facts(item)));
        }

        Candidates = candidates;
        CandidateMap = map;
    }

    /// <summary>The origin slot this adapter instance serves.</summary>
    public ToolContextType ContextType { get; }

    /// <summary>The Tool family the slot requires (CM context → CM Tool).</summary>
    public ToolType ExpectedType { get; }

    /// <summary>The canonical slot token (<c>CM</c>, <c>MF</c> or <c>BQ</c>).</summary>
    public string SlotToken => ToolTokens.ToToken(ContextType);

    /// <summary>One candidate per matching canonical Tool, in the supplied order. Never merged.</summary>
    public IReadOnlyList<ToolPickerCandidatePresentation> Candidates { get; }

    /// <summary>
    /// This adapter's own opaque-key → canonical identity mapping, for the duration of the
    /// interaction. It is the adapter's state, never a declaration that the key IS the identity.
    /// </summary>
    public IReadOnlyList<ToolCandidateEntry> CandidateMap { get; }

    /// <summary>The canonical Tool currently associated with the origin slot, if any.</summary>
    public Guid? AssociatedToolId { get; private set; }

    /// <summary>The latched explicit selection of this interaction, or <c>null</c>.</summary>
    public ToolSelection? Selection => _selection;

    /// <summary>The opaque origin token of this interaction.</summary>
    public string OriginToken => $"{OriginTokenPrefix}-{SlotToken}";

    /// <summary>The supplied expected-type label of the slot.</summary>
    public string ExpectedTypeLabel => SlotToken;

    /// <summary>
    /// Resolves an opaque candidate key to the canonical identity it stands for, or <c>null</c> when
    /// the key does not reference a supplied candidate. It never falls back to display text.
    /// </summary>
    public Guid? ResolveCandidate(string candidateKey) =>
        candidateKey is not null && _itemsByKey.TryGetValue(candidateKey, out var item)
            ? item.ToolId
            : null;

    /// <summary>
    /// Applies exactly one explicit human selection. The first resolution wins: a second selection
    /// event within the same interaction cannot change it, and an unknown key selects nothing.
    /// </summary>
    public ToolSelection? Select(string candidateKey)
    {
        if (_selection is not null)
        {
            return _selection;
        }

        if (ResolveCandidate(candidateKey) is not { } toolId)
        {
            return null;
        }

        _selection = new ToolSelection(toolId, ExpectedType);
        return _selection;
    }

    /// <summary>
    /// Cancels the picker subflow: nothing is selected and the origin association is unchanged.
    /// </summary>
    public ToolSelection? Cancel()
    {
        _selection = null;
        return null;
    }

    /// <summary>
    /// Returns to the origin: the latched selection is released and the association is preserved
    /// exactly as it was before the interaction.
    /// </summary>
    public ToolSelection? Return() => Cancel();

    /// <summary>Records the canonical identity associated with the origin slot (inline create or selection).</summary>
    public void Associate(Guid toolId) => AssociatedToolId = toolId;

    /// <summary>Removes the origin association (the operator cleared the slot).</summary>
    public void ClearAssociation() => AssociatedToolId = null;

    /// <summary>
    /// Builds the supplied picker input. <paramref name="selectedCandidateKey"/> stays <c>null</c>
    /// unless the caller has an explicit selection to present: no step here selects anything.
    /// </summary>
    public ToolPickerPresentation BuildPresentation(
        CommonState state,
        string regionLabel,
        string? query = null,
        string? message = null,
        string? reason = null,
        string? resultSummary = null,
        SharedActionPresentation? createAction = null,
        SharedActionPresentation? cancelAction = null,
        SharedActionPresentation? retryAction = null,
        string? selectedCandidateKey = null)
    {
        var originContext = new List<ToolPickerFactPresentation>();

        if (AssociatedToolId is { } associated)
        {
            // The origin context shows what the slot currently holds; it never invents a Tool fact.
            var item = _itemsByKey.Values.FirstOrDefault(candidate => candidate.ToolId == associated);
            originContext.Add(ToolPickerFactPresentation.Create(
                "Ferramenta associada",
                item is null ? associated.ToString() : $"{item.Reference} — lote {item.Lot}"));
        }

        return ToolPickerPresentation.Create(
            state,
            regionLabel,
            query,
            Candidates,
            selectedCandidateKey,
            OriginToken,
            originContext,
            ExpectedTypeLabel,
            createAction,
            cancelAction,
            retryAction,
            message,
            reason,
            stateActions: null,
            resultSummary);
    }

    /// <summary>
    /// Builds the create-form pre-fill from values already known from the origin context. Unknown
    /// Tool facts are never invented and never defaulted.
    /// </summary>
    public ToolCreatePrefill Prefill(string? reference) =>
        new(reference, null, null, null, []);

    private static string AccessibleContext(ToolSearchItem item) =>
        $"{ToolTokens.ToToken(item.Type)} {item.Reference} lote {item.Lot}";

    private static IReadOnlyList<ToolPickerFactPresentation> Facts(ToolSearchItem item)
    {
        // An absent fact is simply not supplied: never a dash, never a zero, never a false.
        var facts = new List<ToolPickerFactPresentation>
        {
            ToolPickerFactPresentation.Create("Tipo", ToolTokens.ToToken(item.Type)),
            ToolPickerFactPresentation.Create("Referência", item.Reference),
            ToolPickerFactPresentation.Create("Lote", item.Lot),
            ToolPickerFactPresentation.Create(
                "Máquinas",
                string.Join(", ", item.CompatibleMachines.Select(machine => machine.Value))),
        };

        if (item.Quantity is { } quantity)
        {
            facts.Add(ToolPickerFactPresentation.Create("Quantidade", quantity.ToString()));
        }

        if (ToolTokens.ToToken(item.Processo) is { } processo)
        {
            facts.Add(ToolPickerFactPresentation.Create("Processo", processo));
        }

        return facts;
    }
}

/// <summary>
/// The opaque canonical slot tokens of the CM/MF/BQ association regions.
/// </summary>
/// <remarks>
/// The tokens are the stored context tokens (<c>CM</c>, <c>MF</c>, <c>BQ</c>); the hidden and search
/// field names are P2-T04-owned transport names of this surface only.
/// </remarks>
public static class JobOnSlotTokens
{
    /// <summary>The slot token of a context kind.</summary>
    public static string Token(ToolContextType contextType) => ToolTokens.ToToken(contextType);

    /// <summary>The hidden canonical-identity field name of a slot.</summary>
    public static string HiddenField(ToolContextType contextType) => contextType switch
    {
        ToolContextType.Cm => "cmToolId",
        ToolContextType.Mf => "mfToolId",
        _ => "bqToolId",
    };

    /// <summary>The search-input field name of a slot.</summary>
    public static string SearchField(ToolContextType contextType) => contextType switch
    {
        ToolContextType.Cm => "slotQueryCm",
        ToolContextType.Mf => "slotQueryMf",
        _ => "slotQueryBq",
    };

    /// <summary>The three slots in the settled order.</summary>
    public static IReadOnlyList<ToolContextType> All { get; } =
    [
        ToolContextType.Cm,
        ToolContextType.Mf,
        ToolContextType.Bq,
    ];
}

/// <summary>One P2-T04-owned opaque candidate key → canonical Tool identity entry.</summary>
public sealed record ToolCandidateEntry(string Key, Guid ToolId);

/// <summary>One rendered CM/MF/BQ association region of a Job On surface.</summary>
public sealed record JobOnSlotRegion(
    string Token,
    string HiddenFieldName,
    string SearchFieldName,
    Guid? AssociatedToolId,
    string? AssociatedSummary,
    ToolPickerPresentation Picker,
    IReadOnlyList<ToolCandidateEntry> CandidateMap);

/// <summary>
/// The inline Tool create pre-fill of a Job On origin surface.
/// </summary>
/// <remarks>
/// Authority: P2-T04 contract §9.3.7 ("Pre-fill is assistance only"): only values already known from
/// the origin context are supplied, and every unknown Tool fact stays absent.
/// </remarks>
public sealed record ToolCreatePrefill(
    string? Reference,
    string? Lot,
    string? Processo,
    int? Quantity,
    IReadOnlyList<string> Machines);
