<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>DMO.IntegrationTests</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="xunit" />
    <PackageReference Include="Xunit.SkippableFact" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="coverlet.collector" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\DMO.Web\DMO.Web.csproj" />
    <ProjectReference Include="..\..\src\DMO.Infrastructure\DMO.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\DMO.Application\DMO.Application.csproj" />
    <ProjectReference Include="..\..\src\DMO.Domain\DMO.Domain.csproj" />
  </ItemGroup>

</Project>
